apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/external-dns
  prune: true
  validation: client
  patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: "external-dns"
      namespace: "flux-system"
    patch: |-
      - op: replace
        path: "/spec/values/serviceAccount/annotations/eks.amazonaws.com~1role-arn"
        value: arn:aws:iam::111111111111:role/external-dns-service-account-cluster-1
      - op: replace
        path: "/spec/values/txtOwnerId"
        value: cluster-1
