apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ingress
  prune: true
  validation: client
  patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: "ingress-nginx"
      namespace: "flux-system"
    patch: |-
      - op: replace
        path: "/spec/values/controller/service/annotations/service.beta.kubernetes.io~1aws-load-balancer-ssl-cert"
        value: arn:aws:acm:eu-west-1:111111111111:certificate/4694ab7f-022f-4272-b1a2-b8218cce4c8e
